apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-vol
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.163
    path: /exports/git-etc
