apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgress
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.163
    path: /exports/postgres
