apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-vol
spec:
  capacity:
    storage: 512Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.163
    path: /exports/redis
